version: "3.8"

services:
  wol_api:
    image: docker.io/bolferdocker/wolan-api:0.0.2
    network_mode: host
    environment:
      - API_KEY=default_key
      - BROADCAST_ADDRESS=192.168.1.255
      - PORT=9
    restart: unless-stopped
